### ISSUE TITLE
Graphical issue in scrolling (DoDonPachi/Esp Ra.De/Guwange)

### ISSUE THREAD

**Issue by Botvinnik92** [MiSTer-devel/Arcade-Cave_MiSTer#76]
Greetings,
I have noticed a problem in the latest beta core (Cave_20220512), which creates a diagonal line from the upper-left corner of the screen. I have noticed this issue in DoDonPachi (https://youtube.com/shorts/oPjB51r-Ues), Esp Ra.De (https://youtube.com/shorts/IuFgMimjrZI) and Guwange (https://youtube.com/shorts/m_VE-N0zr0Q), but was unable to reproduce it in Dangun Feveron. The attached picture shows the booting screen in Guwange, where it is clearly noticeable:
![IMG_20220512_221604_1](https://user-images.githubusercontent.com/93479629/168169882-4e8b2e19-d4db-4539-b128-e5d5138e9d92.jpg)

I have noticed this problem while using the HDMI output, and only when I used the vertical output mode (when selecting the horizontal mode, the glitch dissapeared immediately). The only 'unusual' feature in my settings is the 'vsync_adjust = 2' option in my MiSTer.ini, so the core was running at 57Hz even in my LCD monitor (FreeSync).
I didn't notice this issue in previous beta versions, and it only happens from time to time.
If there's any other information I can provide which can be useful, please let me know.

Best regards.

**Comment by nullobject** [comment]
Thanks @Botvinnik92.

This is because `vsync_adjust=2` sets the frame buffer in "low latency" mode. Without double buffering you will see screen tearing artifacts with the Cave core.

Try using a different `vsync_adjust` value:

* `vsync_adjust=1`: double buffering enabled at the original refresh (recommended)
* `vsync_adjust=0`: double buffering enabled with forced 60Hz refresh (for compatibility with some fussy displays)

You can set a `vsync_adjust` value just for the Cave core, even if you want to still use low latency mode for everything else:

```
[cave]
vsync_adjust=1
```

Hope this helps, let me know.

**Comment by Botvinnik92** [comment]
Thanks @nullobject, really appreciate it.
As you said, after enabling `vsync_adjust = 1`, I haven't noticed any issues, while maintaing the smooth scrolling.
So, I guess this was a false alarm, with your permission I will close this issue.

Thanks again for your attention, and congrats for this gorgeous core.

**Comment by nullobject** [comment]
@Botvinnik92 No worries, I'm glad that it is running properly now :+1:
